// This file is auto-generated by build.ts. Do not edit directly.

export const BUNDLED_MODES: Record<string, string> = {
  "auditor.md": "---\nname: auditor\ndescription: Code review and quality audit\nstage: audit\ncreated: '2025-12-17'\n---\n\n# Auditor Mode\n\nReview code changes for correctness and quality.\n",
  "coder.md": "---\nname: coder\ndescription: General-purpose coding agent for implementation\nstage: code\ncreated: '2025-12-17'\n---\n\n# Coder Mode\n\nImplement tasks from refined prompts and context.\n",
  "planner.md": "---\nname: planner\ndescription: Task planning and refinement\nstage: plan\ncreated: '2025-12-17'\n---\n\n# Planner Mode\n\nCreate and refine task specifications.\n"
} as const;
