// This file is auto-generated by build.ts. Do not edit directly.

export const BUNDLED_PROVIDERS: Record<string, string> = {
  "codex.md": "---\ncli: codex\nsubcommand: exec\nmodel: gpt-5.3-codex\nunattended_flags:\n  - '--yolo'\noutput_flags:\n  - '--json'\nprompt_style: stdin\nprovider: openai\nconfig_overrides:\n  model_reasoning_effort: medium\n---\n\n",
  "glm.md": "---\ncli: kilo\nsubcommand: run\nmodel: openrouter/z-ai/glm-4.7\nunattended_flags:\n  - '--auto'\noutput_flags: []\nprompt_style: positional\nprovider: openrouter\n---\n",
  "kimi.md": "---\ncli: kimi\nmodel: kimi-k2-thinking-turbo\nunattended_flags:\n  - '--print'\noutput_flags:\n  - '--quiet'\nprompt_style: flag\nprovider: moonshot\n---\n\n",
  "opus.md": "---\ncli: claude\nmodel: claude-opus-4-5\nunattended_flags:\n  - '--dangerously-skip-permissions'\noutput_flags:\n  - '--output-format'\n  - json\nprompt_style: flag\nsafety:\n  max_turns: 20\n  max_budget_usd: 5\nprovider: anthropic\n---\n\n"
} as const;
